# Shell
# shell = { program = "/usr/bin/fish", args = ["tmux attach-session"] }
# shell = "/bin/fish"
shell.program = "/bin/fish"
shell.args = ["--login", "-c", "tmux attach-session"]

# Colors
window.opacity=0.99
# colors.primary.background="#252a34"
import = ["~/.config/alacritty/catppuccin-macchiato.toml"] 

# Mouse
mouse.hide_when_typing=true
